#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#

mount /dev/mmcblk1p1 /mnt
if [ -d /mnt/sysconfig ]; then
        cp -a /mnt/sysconfig/* /etc/sysconfig/.
else
        mkdir /mnt/sysconfig
        cp -a /etc/sysconfig/* /mnt/sysconfig/.
fi
umount /mnt

for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

